service: perfsys-cloud-reports

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  customDomain:
    domainName: reports-${opt:stage, 'dev'}.perfsys.io
  service: ${self:service}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  leadGenerationReportTable: ${self:service}-leadGenerationReport-${self:custom.stage}
  developerWeeklyReportTable: ${self:service}-developerWeeklyReport-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - { "Fn::GetAtt": ["leadGenerationReportTable", "Arn" ] }
        - { "Fn::GetAtt": ["developerWeeklyReportTable", "Arn" ] }
  environment:
    LEAD_GENERATION_REPORT_TABLE_NAME: ${self:custom.leadGenerationReportTable}
    DEVELOPER_WEEKLY_REPORT_TABLE_NAME: ${self:custom.developerWeeklyReportTable}

package:
  exclude:
    - frontend/**

#layers:
#  nodeModules:
#    path: layer/nodejs/node_modules
#    name: ${self:service}-node-modules-${opt:stage, self:provider.stage}
#    description: "Shared node modules"
#    compatibleRuntimes:
#      - nodejs10.x


functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /
          method: GET

  health:
    handler: index.handler
    events:
      - http:
          path: /health
          method: GET
          cors: true

  saveLeadGenerationReport:
    handler: index.handler
    events:
      - http:
          path: /report/lead-generation
          method: POST
          cors: true

  getDeveloperWeeklyReport:
    handler: index.handler
    events:
      - http:
          path: /report/developer/week
          method: POST
          cors: true

  getDeveloperDailyReport:
    handler: index.handler
    events:
      - http:
          path: /report/developer/day
          method: POST
          cors: true

  saveDeveloperAtomicReport:
    handler: index.handler
    events:
      - http:
          path: /report/developer/job
          method: POST
          cors: true

  deleteDeveloperAtomicReport:
    handler: index.handler
    events:
      - http:
          path: /report/developer/job
          method: DELETE
          cors: true
          
  getInfoFromTrello:
    handler: index.handler
    environment:
      TRELLO_API_KEY: ${env:TRELLO_API_KEY}
      TRELLO_OAUTH_TOKEN: ${env:TRELLO_OAUTH_TOKEN}
    events:
      - http:
          path: /trello
          method: GET
          cors: true

resources:
  Resources:
    leadGenerationReportTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.leadGenerationReportTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    developerWeeklyReportTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.developerWeeklyReportTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE

